# Mailmerge SMTP Server Config
# https://github.com/awdeorio/mailmerge
#
# Pro-tip: SSH or VPN into your network first to avoid spam
# filters and server throttling.
#
# Parameters
#   host       # SMTP server hostname or IP
#   port       # SMTP server port
#   security   # Security protocol: "SSL/TLS", "STARTTLS", or omit
#   username   # Username for SSL/TLS or STARTTLS security
#   ratelimit  # Rate limit in messages per minute, 0 for unlimited

[smtp_server]
host = smtp.fastmail.com
port = 465
security = SSL/TLS
username = joelparkerhenderson@fastmail.com
ratelimit = 0

# Example: GMail
# [smtp_server]
# host = smtp.gmail.com
# port = 465
# security = SSL/TLS
# username = YOUR_USERNAME_HERE
# ratelimit = 0

# Example: SSL/TLS
# [smtp_server]
# host = smtp.mail.umich.edu
# port = 465
# security = SSL/TLS
# username = YOUR_USERNAME_HERE
# ratelimit = 0

# Example: STARTTLS security
# [smtp_server]
# host = newman.eecs.umich.edu
# port = 25
# security = STARTTLS
# username = YOUR_USERNAME_HERE
# ratelimit = 0

# Example: Plain security
# [smtp_server]
# host = newman.eecs.umich.edu
# port = 25
# security = PLAIN
# username = YOUR_USERNAME_HERE
# ratelimit = 0

# Example: XOAUTH
# Enter your token at the password prompt.  For Microsoft OAuth
# authentication, a token can be obtained with the oauth2ms tool
# https://github.com/harishkrupo/oauth2ms
# [smtp_server]
# host = smtp.office365.com
# port = 587
# security = XOAUTH
# username = username@example.com

# Example: No security
# [smtp_server]
# host = newman.eecs.umich.edu
# port = 25
# ratelimit = 0
